services:
  # SQL Server 22 db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: logbook_db
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=InternshipLog2026!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  # .net8
  api:
    build:
      context: ./InternshipLogbook.API
      dockerfile: Dockerfile
    container_name: logbook_api
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=InternshipLogbookDB;User Id=sa;Password=InternshipLog2026!;TrustServerCertificate=True;
      - Jwt__Key=7A912F3B4C5D6E8F9A0B1C2D3E4F5A6B7C8D9E0F1A2B3C4D5E6F7A8B9C0D1E2F
      - Jwt__Issuer=InternshipLogbookAPI
      - Jwt__Audience=InternshipLogbookFrontend
    ports:
      - "5203:8080"
    networks:
      - app-network

  # Angular
  ui:
    build:
      context: ./internship-logbook-ui
      dockerfile: Dockerfile
    container_name: logbook_ui
    depends_on:
      - api
    ports:
      - "4200:80"
    networks:
      - app-network

# persist data
volumes:
  sql_data:

networks:
  app-network:
    driver: bridge